definitions:
  domain.Dentista:
    properties:
      apellido:
        type: string
      matricula:
        type: string
      nombre:
        type: string
    required:
    - apellido
    - matricula
    - nombre
    type: object
  domain.Paciente:
    properties:
      apellido:
        type: string
      dni:
        type: string
      domicilio:
        type: string
      fechaAlta:
        type: string
      nombre:
        type: string
    required:
    - apellido
    - dni
    - domicilio
    - fechaAlta
    - nombre
    type: object
  domain.Turno:
    properties:
      descripcion:
        type: string
      fecha:
        type: string
      hora:
        type: string
      idDentista:
        type: integer
      idPaciente:
        type: integer
    required:
    - descripcion
    - fecha
    - hora
    - idDentista
    - idPaciente
    type: object
  domain.TurnoByDni:
    properties:
      dentista:
        $ref: '#/definitions/domain.Dentista'
      descripcion:
        type: string
      fecha:
        type: string
      hora:
        type: string
      paciente:
        $ref: '#/definitions/domain.Paciente'
    required:
    - dentista
    - descripcion
    - fecha
    - hora
    - paciente
    type: object
  domain.TurnoDos:
    properties:
      descripcion:
        type: string
      dniPaciente:
        type: string
      fecha:
        type: string
      hora:
        type: string
      matriculaDentista:
        type: string
    required:
    - descripcion
    - dniPaciente
    - fecha
    - hora
    - matriculaDentista
    type: object
  handler.Request:
    properties:
      apellido:
        type: string
      matricula:
        type: string
      nombre:
        type: string
    type: object
  handler.RequestPaciente:
    properties:
      apellido:
        type: string
      dni:
        type: string
      domicilio:
        type: string
      fechaAlta:
        type: string
      nombre:
        type: string
    type: object
  handler.RequestTurno:
    properties:
      descripcion:
        type: string
      fecha:
        type: string
      hora:
        type: string
      idDentista:
        type: integer
      idPaciente:
        type: integer
    type: object
  web.errorResponse:
    properties:
      code:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact:
    name: Alejandra Marin - Vanesa Vilte
    url: https://github.com/AlejaMarin/Desafio-2-Go
  description: Implementación de una API que permite administrar la reserva de turnos
    para una clínica odontológica.
  title: SISTEMA DE RESERVA DE TURNOS
  version: "1.0"
paths:
  /dentistas:
    post:
      consumes:
      - application/json
      description: Crear dentista
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Body dentist
        in: body
        name: dentista
        required: true
        schema:
          $ref: '#/definitions/domain.Dentista'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Dentista'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Agregar dentista
      tags:
      - Dentistas
  /dentistas/{id}:
    delete:
      description: Eliminar un dentista por ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Eliminar dentista
      tags:
      - Dentistas
    get:
      description: Obtener dentista por ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Dentista'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Obtener dentista
      tags:
      - Dentistas
    patch:
      consumes:
      - application/json
      description: Actualizar un dentista por alguno de sus campos
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Dentista'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar dentista
      tags:
      - Dentistas
    put:
      consumes:
      - application/json
      description: Actualizar dentista por ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Body dentist
        in: body
        name: dentista
        required: true
        schema:
          $ref: '#/definitions/domain.Dentista'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Dentista'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar dentista
      tags:
      - Dentistas
  /pacientes:
    post:
      consumes:
      - application/json
      description: Crear paciente
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Body patient
        in: body
        name: paciente
        required: true
        schema:
          $ref: '#/definitions/domain.Paciente'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Paciente'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Agregar paciente
      tags:
      - Pacientes
  /pacientes/{id}:
    delete:
      description: Eliminar un paciente por ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Eliminar paciente
      tags:
      - Pacientes
    get:
      description: Obtener paciente por ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Paciente'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Obtener paciente
      tags:
      - Pacientes
    patch:
      consumes:
      - application/json
      description: Actualizar un paciente por alguno de sus campos
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RequestPaciente'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Paciente'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar paciente
      tags:
      - Pacientes
    put:
      consumes:
      - application/json
      description: Actualizar paciente por ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Body patient
        in: body
        name: dentista
        required: true
        schema:
          $ref: '#/definitions/domain.Paciente'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Paciente'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar paciente
      tags:
      - Pacientes
  /turnos:
    get:
      description: Obtener turno por DNI del paciente
      parameters:
      - description: dni
        in: query
        name: dni
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.TurnoByDni'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Obtener turno
      tags:
      - Turnos
    post:
      consumes:
      - application/json
      description: Agregar turno
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Body shift
        in: body
        name: turno
        required: true
        schema:
          $ref: '#/definitions/domain.Turno'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Turno'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Agregar turno
      tags:
      - Turnos
  /turnos/{id}:
    delete:
      description: Eliminar un turno por ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Eliminar turno
      tags:
      - Turnos
    get:
      description: Obtener turno por ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Turno'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Obtener turno
      tags:
      - Turnos
    patch:
      consumes:
      - application/json
      description: Actualizar un turno por alguno de sus campos
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RequestTurno'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Turno'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar turno
      tags:
      - Turnos
    put:
      consumes:
      - application/json
      description: Actualizar turno por ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Body shift
        in: body
        name: turno
        required: true
        schema:
          $ref: '#/definitions/domain.Turno'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Turno'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar turno
      tags:
      - Turnos
  /turnos/pacientedentista:
    post:
      consumes:
      - application/json
      description: Agregar turno por DNI del paciente y matrícula del dentista
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Body shift
        in: body
        name: turno
        required: true
        schema:
          $ref: '#/definitions/domain.TurnoDos'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Turno'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Agregar turno
      tags:
      - Turnos
schemes:
- http
swagger: "2.0"
